# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSDemo
  
  pod 'AFNetworking', '~> 4.0'
  pod 'Mantle'
  pod 'Masonry‘
  pod 'SDWebImage', '~> 5.0'
  pod 'ReactiveCocoa', '~> 2.5'
  

  target 'iOSDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSDemoUITests' do
    # Pods for testing
  end

end
